### ISSUE TITLE
Using Predicate Pushdown still reads records that don't match.

### ISSUE THREAD

**Issue by danosipov** [HotelsDotCom/corc#12]
To test, in OrcFileTest.readStringPredicatePushdownIncludeStripe test, add a few more records to the writer that don't match the predicate.

```
  public void readStringPredicatePushdownIncludeStripe() throws IOException {
    TypeInfo typeInfo = TypeInfoFactory.stringTypeInfo;

    try (OrcWriter writer = getOrcWriter(typeInfo)) {
      writer.addRow("hello");
      writer.addRow("goodbye");
    }

    StructTypeInfo structTypeInfo = new StructTypeInfoBuilder().add("a", TypeInfoFactory.stringTypeInfo).build();

    SearchArgument searchArgument = SearchArgumentFactory.newBuilder().startAnd().equals("a", "hello").end().build();

    OrcFile orcFile = OrcFile.source().columns(structTypeInfo).schemaFromFile().searchArgument(searchArgument).build();
    Tap<?, ?, ?> tap = new Hfs(orcFile, path);

    List<Tuple> list = Plunger.readDataFromTap(tap).asTupleList();

    assertThat(list.size(), is(1)); //Fails
  }
```

**Comment by nahguam** [comment]
Hi, predicate pushdown currently only skips reading a row group if no record matches the SearchArgument. In other words, if 1 record in a 10,000 row group matches then the entire row group is read. It should be viewed as a performance optimisation only and an equivalent filter still has to be applied.

Having said that, I am currently working on a patch that also applies the SearchArgument as a filter which will achieve what you are looking for.

**Comment by danosipov** [comment]
I figured that's what was happening, however, the developer experience is very non-intuitive. Having the condition applied as a filter on a pipe would be great!

**Comment by nahguam** [comment]
Hi Dan, 

I've opened a branch that applies the `SearchArgument` at the row level in the `RecordReader`. Would you like to give it a spin? PR is here https://github.com/HotelsDotCom/corc/pull/13

**Comment by danosipov** [comment]
Worked in my test case - this is great, thanks!
