### ISSUE TITLE
CoGroup issue with Cascading on Tez

### ISSUE THREAD

**Issue by Pierre-Antoine** [HotelsDotCom/corc#21]
Hi,

I opened a thread on the Cascading user group (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cascading-user/GDauDn91NtA/BLjWjL7GAwAJ) but it seems to be related to the ORC scheme.

When using the Corc scheme and a CoGroup operation with a different tap (coming from an avro file for example), about half the lines are lost in the output (looks like some of the reducers aren't writing anything). More details and a piece of code are contained in the thread above. I might be able to send a test class with data if needed. We don't have this issue with another ORC Scheme (https://github.com/branky/cascading.hive).

**Comment by patduin** [comment]
Thanks for reporting. We'll try to look into this as soon as possible.

**Comment by nahguam** [comment]
Hi @Pierre-Antoine,

Thanks for this. If you are able, would you be able to retry with [Counters](http://docs.cascading.org/cascading/3.0/javadoc/cascading-core/cascading/operation/state/Counter.html) on the pipe before and after the join to isolate where the records are being filtered out (during read or join)? 

I notice that your `CoGroup` is joining on `new Fields("id")`, i.e no type is declared. What is the type on both sides of the join?

**Comment by Pierre-Antoine** [comment]
We analyzed this with the counters on our cluster and lines are filtered after the join operation. Read operation is normal (no loss). 
Indeed no type is declared, it should be a String type. But even by setting the type, it does not solve the issue.

**Comment by nahguam** [comment]
Thanks, what are the types in the underlying ORC and Avro files? String? (not a variant like HiveVarchar?). 

Perplexing that you say it works if you pre-trim the strings and works in Hadoop2MR1 and works in another ORC scheme. I've tried replicating here but no luck.

**Comment by Pierre-Antoine** [comment]
Yes, it's all string in both files.

The ORC file also needs to be partionned to replicate the issue (several "part" files) and parallelization set to more than 1. I can send you my source files if needed.

**Comment by nahguam** [comment]
That would be a help. Is it something you can make public on your github?

**Comment by Pierre-Antoine** [comment]
I will prepare the files to remove potential sensitive data and add them on Github.

**Comment by Pierre-Antoine** [comment]
I just pushed a test class + data here: https://github.com/Pierre-Antoine/DataTest

Should end up with 1000 lines but only got 769.

**Comment by nahguam** [comment]
Thanks for this. Are you sure you're using corc? If I do this: 

```
OrcFile.source().declaredFields(CHAMPS_OUT_VALUES).schemaFromFile().build();
```

...it will throw an exception as `CHAMPS_OUT_VALUES` does not declare types.

What's in `fr.edf.distribution.linky.lpt.support.OrcTapFactory`?

**Comment by nahguam** [comment]
Also, which Avro Scheme are you using? I've assumed `cascading.avro:avro-scheme:2.5.0` but that doesn't seem to work with Tez - NPE trying to get the `mapreduce.job.inputformat.class` from the conf. It's ok with MR1.

**Comment by Pierre-Antoine** [comment]
I just commited the missing class. We use indeed cascading.avro:avro-scheme:2.5.0.

**Comment by Pierre-Antoine** [comment]
We also use Tez 0.6.2, which is not the latest version.

**Comment by nahguam** [comment]
Thanks. Got it working (needed to set `new-api:false`). Output looks ok:

```
    // Pipes
    Pipe avroPipe = new Pipe("inAvro");
    Pipe orcPipe = new Pipe("inOrc");

    String group = "rowCounts";
    Pipe avroCount = new Each(avroPipe, new Counter(group, "avro"));
    Pipe orcCount = new Each(orcPipe, new Counter(group, "orc"));

    SubAssembly assembly = new CoGroupAssembly(orcCount, avroCount);
    Pipe tail = new Each(assembly, new Counter(group, "join"));

    // Taps
    Hfs avroTap = new Hfs((Scheme) new AvroScheme(SCHEMA_JSON2), dataDir + "inAvro");

    Tap orcTap = new OrcTapFactory().createSource(CHAMPS_OUT_VALUES, dataDir + "inPdkOrc");

    File outDirectory = new File(temporaryFolder.getRoot(), "out");
    Tap out = new Hfs(new TextDelimited(CHAMPS_OUT_VALUES, ";"), outDirectory.getAbsolutePath());

    // Flow
    FlowDef flowDef = FlowDef.flowDef().addSource(avroPipe, avroTap).addSource(orcPipe, orcTap).addTailSink(tail, out);

    Properties properties = new Properties();
    properties.setProperty(FlowRuntimeProps.GATHER_PARTITIONS, "5");
    properties.setProperty("hive.exec.orc.default.block.size", "" + 128L * 1024 * 1024);
    properties.setProperty("mapred.mapper.new-api", "false");

    Flow flow = new Hadoop2TezFlowConnector(properties).connect(flowDef);
    flow.complete();

    // Stats
    CascadingStats stats = flow.getStats();
    for (String counter : stats.getCountersFor(group)) {
      long value = stats.getCounterValue(group, counter);
      System.out.println(String.format("%s:%s - %d", group, counter, value));
    }

    // rowCounts:orc - 1001
    // rowCounts:join - 1001
    // rowCounts:avro - 996
```

**Comment by Pierre-Antoine** [comment]
Have you also checked the number of lines in the generated file?

**Comment by nahguam** [comment]
```
    int count = 0;
    File[] files = outDirectory.listFiles();
    for (File file : files) {
      if (file.getName().startsWith("part")) {
        count += Files.readLines(file, StandardCharsets.UTF_8).size();
      }
    }
    System.out.println(count);

    // 1001
```

**Comment by Pierre-Antoine** [comment]
Still can't make it work. Here are the versions I have in my pom:
`<hive.version>1.2.1</hive.version>
<guava.version>11.0.2</guava.version>
<hadoop.version>2.6.0</hadoop.version>
<avro.version>1.7.7</avro.version>
<commons-io.version>2.4</commons-io.version>
<cascading.version>3.1.1</cascading.version>
<cascading-avro.version>2.5.0</cascading-avro.version>
<plunger.version>3.0.2</plunger.version>
<corc.version>2.0.3</corc.version>
<kryo.version>2.22</kryo.version>
<tez.version>0.6.2</tez.version>`

**Comment by nahguam** [comment]
Aha, replicated it.

cascading 3.0.2:
```
rowCounts:orc - 1001
rowCounts:join - 1001
rowCounts:avro - 996
1001
```

cascading 3.2.1:
```
rowCounts:orc - 1001
rowCounts:join - 769
rowCounts:avro - 996
769
```

**Comment by nahguam** [comment]
I've converted both the Avro and ORC data to text (removing Avro and Corc from the equation) and it's still happening, so I think this is a Cascading issue, introduced in 3.1.0. We should continue the discussion on the cascading-user mailing list.

**Comment by Pierre-Antoine** [comment]
Weird, i can't replicate it with CSV files.

**Comment by nahguam** [comment]
I've pushed my tests here: https://github.com/nahguam/corc-issue21

I ran both the Avro and ORC files through an identity flow sinking to `TextDelimited` then copied the  original test and sourced from the text files. The ORC files had compacted into a single file so I ran it through `split -l 150 part-v000-o000-00000` to give me 7 files.

**Comment by Pierre-Antoine** [comment]
When i remove the typing in the fields, the join is OK with text files but not with ORC/Avro.

`private static final Fields FIELD_ID_PDK = new Fields("id_pdk", String.class);
  private static final Fields FIELD_VALUE = new Fields("value", String.class);`

to `private static final Fields FIELD_ID_PDK = new Fields("id_pdk");
  private static final Fields FIELD_VALUE = new Fields("value");`

**Comment by Pierre-Antoine** [comment]
I also replicate the issue when a key has not same length as the other. There is indeed a parasite line in the data test that causes the issue...

**Comment by Pierre-Antoine** [comment]
@nahguam Hey, is it possible to delete your repo corc-issue21? Thanks!

**Comment by nahguam** [comment]
@Pierre-Antoine done :)
